variable "platform_id" {}
variable "zone" {}
variable "resource_core" {}
variable "resource_memory" {}
variable "image_id" {}
variable "subnet_id" {}
variable "nat" {}
variable "instance_group_name" {}
variable "user_data" {}
variable "sa_id" {}