FROM amazoncorretto:11

ENV JENKINS_VERSION="2.303"

EXPOSE 50000

EXPOSE 8080

WORKDIR /var

RUN curl -LO https://get.jenkins.io/war/${JENKINS_VERSION}/jenkins.war

ENTRYPOINT ["java"]

CMD ["-jar", "jenkins.war"]
