FROM ubuntu:latest

ENV JENKINS_VERSION="2.303"

EXPOSE 50000

EXPOSE 8080

RUN apt update -y && apt dist-upgrade -y && apt install -y curl openjdk-11-jdk && apt autoremove -y

WORKDIR /var

RUN curl -LO https://get.jenkins.io/war/${JENKINS_VERSION}/jenkins.war

ENTRYPOINT ["java"]

CMD ["-jar", "jenkins.war"]

