FROM node:17

EXPOSE 3000

ENV VCAP_APP_HOST="0.0.0.0"

RUN mkdir /var/nodejs

WORKDIR /var/nodejs

RUN git clone https://github.com/simplicitesoftware/nodejs-demo.git .

RUN npm install

CMD [ "npm", "start"]
