---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nfs
  labels:
    app: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        volumeMounts:
        - name: nfs-volume
          mountPath: "/opt/log"
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc