---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mb-pvc
spec:
  volumeMode: Filesystem
  storageClassName: host-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi