variable "zone" {}
variable "network_name" {}
variable "public_subnet_name" {}
variable "public_subnet_cidr" {}
variable "private_subnet_name" {}
variable "private_subnet_cidr" {}
variable "nat_instance_name" {}
variable "nat_instance_platform_id" {}
variable "nat_instance_core" {}
variable "nat_instance_memory" {}
variable "nat_instance_image_id" {}
variable "nat_instance_ip" {}
variable "vm_pub_instance_name" {}
variable "vm_pub_instance_platform_id" {}
variable "vm_pub_instance_core" {}
variable "vm_pub_instance_memory" {}
variable "vm_pub_instance_image_id" {}
variable "vm_pri_instance_name" {}
variable "vm_pri_instance_platform_id" {}
variable "vm_pri_instance_core" {}
variable "vm_pri_instance_memory" {}
variable "vm_pri_instance_image_id" {}