variable "zone" {}
variable "folder_id" {}
variable "network_name" {}
variable "public_subnet_name" {}
variable "public_subnet_cidr" {}
variable "vm_instance_group_name" {}
variable "vm_instance_platform_id" {}
variable "vm_instance_core" {}
variable "vm_instance_memory" {}
variable "vm_instance_image_id" {}
