---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nmt
  labels:
    app: app-nmt
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 80%
      maxUnavailable: 80%
  selector:
    matchLabels:
      app: app-nmt
  template:
    metadata:
      labels:
        app: app-nmt
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
         - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "8443"