apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 1180
        env:
          - name: HTTP_PORT
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  selector:
    app: nginx
  ports:
    - name: web-nginx
      port: 9001
      targetPort: 80
    - name: web-multitool
      port: 9002     
      targetPort: 1180

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: multitool
spec:
  containers:
    - name: multitool-pod
      image: wbitt/network-multitool
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080