{
 "title": "Node Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance)(rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(rate(node_load1{}[$__rate_interval]))",
     "legendFormat": "Load Average 1"
    },
    {
     "expr": "avg by (instance)(rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "Load Average 5"
    },
    {
     "expr": "avg by (instance)(rate(node_load15{}[$__rate_interval]))",
     "legendFormat": "Load Average 15"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"})\r",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "avg(node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"})",
     "legendFormat": "Availible Memory"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "Free Space"
    },
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"ext4\",instance=\"nodeexporter:9100\",job=\"nodeexporter\",mountpoint=\"/\"}",
     "legendFormat": "Available Space"
    },
    {}
   ]
  }
 ]
}